baseURL = "https://www.bionicpo.com/"
locale = "en-us"
enableRobotsTXT = true
title = "Bionic Prosthetics & Orthotics"

[module]
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"

[taxonomies]
  category = "categories"

[params]
  gtmID = "GTM-5WTFB2L2"
  googleAdsIDs = ["AW-677614629", "AW-849212221"]
  brandColor = "#1D3F96"
  accentColor = "#F2994A"

[params.contactPoint]
  contactType = "customer service"
  areaServed = "US"
  availableLanguage = "English"
